### ISSUE TITLE
Unable to install pyportus from source

### ISSUE THREAD

**Issue by stephenxudong** [ccp-project/portus#82] opened 2019-12-21 10:21 UTC
I have to build **pyporuts** from source since the latest python version of it could not be found in `pip`.  I followed the instructions in `python/README.md` but could not proceed with it.

System Info: 
```
Ubuntu 18.04
Linux kernel: 4.15.0-70-generic
Python: Python 3.6.0 (default)[GCC 7.4.0] on linux
pip: Python3-pip
cargo: cargo 1.37.0
rustc: rustc 1.37.0
```

I installed `rustc & cargo` by `sudo apt install rustc` and installed `setuptool_rust` by `sudo pip3 install setuptool_rust` . I also modified build.py in setuptool_rust following the README.

Error Message:
```
cargo rustc +nightly --lib --manifest-path Cargo.toml --features pyo3/python3 pyo3/extension-module --verbose -- --crate-type cdylib
   Compiling spin v0.4.10
error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/stephen/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.4.10/src/lib.rs:6:35
  |
6 | #![cfg_attr(feature = "const_fn", feature(const_fn))]
  |                                   ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `spin`.

To learn more, run the command again with --verbose.
error: cargo failed with code: 101
```

I found it doesn't compile whether or not add `nightly` in build.py.

Looking forward to your kind help.  Thanks!

**Comment by akshayknarayan** [comment] 2020-01-06 05:36
Does this issue still occur for you? Using `make python`, I cannot reproduce.

I would suggest using `rustup` instead of apt rust, and using `rustup override set nightly`.

Closing for now, but feel free to reopen if the issue persists. Thanks!

**Closed by akshayknarayan** 2020-01-06 05:36 UTC
